### PR TITLE
Ansi codes

### PR DESCRIPTION
**Pull request by RingMan**
The zprint.ansi/color-str function accepts multiple ANSI codes, but the current ::color spec limits color map values to only the color name (missing white, though). These commits expand the ::color spec to allow a single ANSI code or a collection of them. They also fix a couple of codes and add more to allow for additional styling. The *-off codes are useful for conjoining with existing codes to turn off an existing attribute.

Thank you for this wonderful library

### CODE REVIEW

**Comment by RingMan** [comment]
I realized after creating the pull request that I had broken a spec test. I don't like the refactored spec quite as much as the first, but it fits better into the explain-more mechanism.

There are 4 tests that still fail on my machine, but they fail for me on the master branch as well. I noticed it was the tests checking the count of characters when printing with and without color using with-out-str. My counts are 1 character more. I'm on a Windows 10 system that uses carriage return and linefeed for line endings. Linux only uses linefeed. That's probably the difference.

If you like what you see, one of us can rebase or squash the branch to create a cleaner history. Thanks.

**Comment by kkinnear** [comment]
Thanks so much to doing this!  I haven't had a chance to look at it yet, as I'm deep in some re-architecture to fix a bunch of issues recently discovered with how comments are handled.  I will almost certainly include this in the next release.   The good news is that the considerable changes I'm making right now don't have anything to do with what you've done (or so I surmise).  Thanks as well for noticing the reliance on LF (as opposed to CR/LF) in some of the tests.  I have to believe that I can fix that without too much trouble.  Sounds like I shouldn't be using `with-out-str` in tests, which is something I hadn't ever thought about.  More later as I digest what you've done.

**Comment by kkinnear** [comment]
I didn’t get this into 1.0.0, because I had to get it out and I had gotten caught up in a bunch of bug fixing which delayed me. A lot. 

But I haven’t forgotten about this, and will dive into it next. Thanks again for contributing this work.

**Comment by RingMan** [comment]
Congrats on the 1.0.0 release. You've been busy! I went ahead and rebased the ansi-codes branch onto your current master. I did notice 3 more tests that fail on a checkout of master. It's the ones that try to run multiple zprints in the same JVM. Might be another Windows vs Linux thing.

**Comment by RingMan** [comment]
I just tried this from the REPL:

```clojure
(czprint-fn defn {:color-map {:none :none}})
```
If you simply set the color to `:none` it should work with both light and dark themes. Those elements will just be the same color as for ordinary `zprint`.

Doing that on the master branch complains that `:none` isn't one of the color codes. But it works on the branch you just integrated.

I agree it's very hard to have one set of colors that look nice with both a dark and a light background. Having a light theme and a dark theme makes a lot of sense. That said, you can also set a _background_ color for each element. Specifying both the foreground and background colors almost works. But then the problem is spaces. Leading spaces and blank lines look different from everything else. However, if `:space` also had an entry, then it's just that the right margin looks ragged, but the text is otherwise very readable. Anyway, with that approach every value in the color map would look something like:

```clojure
;[:back-<a-light-color> :<color-that-looks-good-with-it>]
[:back-bright-white :black]
```
I'd rather not attempt a scheme just yet. I plan to submit another pull request soon that lets you apply color to more kinds of elements. If you like it, that would result in more entries in the color map, meaning any color styles would need to be updated.

Thanks for integrating this. Glad it went well.

**Comment by RingMan** [comment]
I just pushed a `dev` branch to my fork. It's based off your 1.0.0 master and includes the commits from both of my pull requests. The HEAD of that branch defines the color map I've been using. I use the cmder console for Windows with a variant of the gruvbox dark theme. I switched between a number of dark themes on my console and they all looked pretty readable. Interestingly enough, I also switched to gruvbox light and solarized light and they both looked fine too. Feel free to use it as a style.

I think the main thing to avoid is coloring any elements `:black` since that is the default background color slot.

**Comment by kkinnear** [comment]
Thanks, this is now in 1.0.1.

**Comment by kkinnear** [comment]
Actually, I think I didn't pick up the `dev` branch color map, as I look at this more closely.  I'll see if I can get that and make it a style.

**Pull request closed without merging**
