### PR TITLE
Thread safety

### PR DESCRIPTION
**Pull request by fazzone**
Hi, I was experimenting with using zprint to pretty-print our entire Clojure codebase, so I basically tried to pmap it over all the source files, and I discovered that zprint is not thread-safe due to `with-redefs`.  So I thought I would try just making every redef'd def `^:dynamic` and using `binding` instead, and it seems to work!  Not sure if there are other reasons to prefer `with-redefs` but being able to call zprint from multiple threads is pretty sweet for my use-case.

### CODE REVIEW

**Comment by kkinnear** [comment]
Thanks for not only bringing this up, but finding a likely solution to this problem!  I hadn't really thought about thread-safety for multiple invocations of zprint, oddly enough, though it is multithreaded itself.   I've been away for a bit, but will explore this approach and get back to you in the next few days.

**Comment by kkinnear** [comment]
I worked on this quite a bit last weekend, and I'm pleased to say that you certainly nailed a very solid solution.  It seems to work well with all of my tests so far.  The only reason why I'm not ecstatic about this approach is because it seems to cost 5-7% in performance.  My testing indicates that the `^:dynamic` is what is costing the performance.  That might not seem like a lot, but I've worked hard on performance, and I've spent days to get each 5-7% of performance improvement I've achieved.  So I'm not wild about losing ground there.  Particularly since many of the use cases for zprint don't care about thread safety, the zprint-filter being the obvious one (which reads stdin and writes stdout).  It is already multithreaded inside, and there is no way to have it process two files at once.  On the other hand, I am excited about possibly uplifting lein-zprint to process multiple files at once, which would be a performance plus and something I never considered prior to your bringing this up.  

I have worked out what seems like an alternative approach and I wanted to see if you had any feedback.  I have figured out how to not lose performance and have it be thread safe as long as all of the threads are processing the same kind of input -- either all source-code that is parsed, or all Clojure structures in memory.  Unless I've misunderstood your use-case, that would be fine for what you are doing.  I think it would be fine for almost anything anyone would do.  I really can't imagine the use-case where you run zprint on source code and zprint on structures at the same time.  Well, I suppose I can, but it is likely pretty rare.  While it isn't as general (or elegant) as your approach, this alternative approach doesn't lose any performance because it doesn't require all of the `zfns` to be `^:dynamic`.  If you try to run two different kinds of zprint simultaneously, the second one will throw an exception telling you that you can't do that, as opposed to just failing in some arbitrary way.

The alternative is to have different code for the zprint-filter and the library, which is certainly possible, but becomes something of a maintenance headache over time.  Not to mention,
that other people use the library to run other places, and they would also lose performance.
So, I'm inclined to trade off general multithreading in favor of keeping the performance, and go with this less general but hopefully sufficient multithreading.

What do you think about that?

**Comment by fazzone** [comment]
At the time I realized I couldn't run zprint from multiple threads, I did not know that zprint itself was multithreaded.  So that definitely makes a lot more sense.  The solution that you mentioned would work fine.  It's awesome that it can be detected and a sensible error message can be shown, it took me a while to figure out what was going on!  Feel free to commit over this or close it.

**Comment by kkinnear** [comment]
I finally got the "fix" for this released.  The code you offered was dramatically simpler, totally correct, and substantially more general than what I finally implemented.  Moreover, it worked with graalvm, which mine mostly didn't.  However, it cost 7% +/- in performance, largely I think because of the dynamic variables used for function lookups (since there are a lot of function lookups).  So, the code I have now doesn't allow mixed format multi-threading, but it does run at the same speed the old code did.

**Pull request closed without merging**
